# Generated by Django 3.2.5 on 2021-08-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptno', models.IntegerField()),
                ('dname', models.TextField()),
                ('loc', models.TextField()),
            ],
        ),
    ]
